[package]
name = "cifar-infer"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
publish = false
autobins = false

[[bin]]
name = "cifar-infer"
path = "src/main.rs"

[[bin]]
name = "cifar-train"
path = "src/train.rs"

[dependencies]
burn = { version = "=0.20.0", default-features = false, features = ["std", "ndarray", "autodiff"] }
ndarray = "=0.16.1"
ndarray-npy = { version = "=0.9.1", default-features = false, features = ["compressed_npz"] }

[profile.release]
codegen-units = 1
lto = "thin"
strip = true
