[project]
name = "inspect-ai-benches"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "inspect-ai>=0.3.217",
    "inspect-evals[all,ifeval,scicode,terminal-bench-2]>=0.10.0",
    "inspect-cyber>=0.1.0",
    "instruction-following-eval>=0.1.0",
    "openai>=2.26.0",
]

[dependency-groups]
ifeval = [
    "instruction-following-eval",
]

[tool.uv.sources]
instruction-following-eval = { git = "https://github.com/josejg/instruction_following_eval" }
