version: '3.9'
services:
  default:
    build:
      context: ./environment
    command:
    - sh
    - -c
    - sleep infinity
    init: true
    shm_size: 1gb
    mem_limit: 8g
    cpus: 2
    working_dir: /app
    x-default: true
