services:
  default:
    build:
      context: ./environment
    command:
    - sh
    - -c
    - sleep infinity
    init: true
    network_mode: host
    shm_size: 1gb
    mem_limit: 8g
    cpus: 8
    working_dir: /app
    x-default: true
