-- Schema Description — use this to understand the intended schema.
-- There is no SQL DDL here intentionally; derive the correct SQL from
-- the descriptions below and from test failures.
--
-- TABLE: users
--   id          INTEGER PRIMARY KEY
--   username    TEXT    UNIQUE NOT NULL
--   email       TEXT    UNIQUE NOT NULL
--   created_at  TEXT    NOT NULL  DEFAULT datetime('now')
--   is_active   INTEGER NOT NULL  DEFAULT 1
--
-- TABLE: products
--   id          INTEGER PRIMARY KEY
--   name        TEXT    NOT NULL
--   category    TEXT    NOT NULL
--   price       REAL    NOT NULL  CHECK(price > 0)       -- strictly positive, not zero
--   stock       INTEGER NOT NULL  DEFAULT 0  CHECK(stock >= 0)
--   created_at  TEXT    NOT NULL  DEFAULT datetime('now')
--
-- TABLE: orders
--   id          INTEGER PRIMARY KEY
--   user_id     INTEGER NOT NULL  REFERENCES users(id)    ON DELETE CASCADE
--   product_id  INTEGER NOT NULL  REFERENCES products(id)
--   quantity    INTEGER NOT NULL  CHECK(quantity > 0)
--   total       REAL    NOT NULL
--   ordered_at  TEXT    NOT NULL  DEFAULT datetime('now')
--
-- TABLE: reviews
--   id          INTEGER PRIMARY KEY
--   user_id     INTEGER NOT NULL  REFERENCES users(id)    ON DELETE CASCADE
--   product_id  INTEGER NOT NULL  REFERENCES products(id)
--   rating      INTEGER NOT NULL  CHECK(rating BETWEEN 1 AND 5)
--   comment     TEXT    (nullable)
--   reviewed_at TEXT    NOT NULL  DEFAULT datetime('now')
--   UNIQUE(user_id, product_id)
--
-- TABLE: categories
--   id          INTEGER PRIMARY KEY AUTOINCREMENT
--   name        TEXT    NOT NULL UNIQUE
--   parent_id   INTEGER  REFERENCES categories(id) ON DELETE SET NULL
--   created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--
-- TABLE: product_price_history
--   id          INTEGER PRIMARY KEY AUTOINCREMENT
--   product_id  INTEGER NOT NULL  REFERENCES products(id) ON DELETE CASCADE
--   old_price   REAL    NOT NULL   -- the price BEFORE the update
--   new_price   REAL    NOT NULL   -- the price AFTER the update
--   changed_at  TEXT    NOT NULL  DEFAULT datetime('now')
--
-- INDEXES:
--   idx_orders_user_id      ON orders(user_id)
--   idx_orders_product_id   ON orders(product_id)
--   idx_reviews_product_id  ON reviews(product_id)
--   idx_products_category   ON products(category)
--   idx_active_categories   ON categories(name) WHERE parent_id IS NOT NULL
--
-- TRIGGERS:
--   trg_update_stock      : AFTER INSERT ON orders FOR EACH ROW
--                           UPDATE products SET stock = stock - NEW.quantity
--                           WHERE id = NEW.product_id
--   trg_log_price_change  : AFTER UPDATE OF price ON products FOR EACH ROW,
--                           ONLY when OLD.price != NEW.price,
--                           INSERT INTO product_price_history(product_id, old_price, new_price)
--                           VALUES (OLD.id, OLD.price, NEW.price)
